/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'principal' : Principal,
  'timestamp' : Timestamp,
  'details' : string,
  'eventType' : AuditEventType,
}
export interface AiAnalytics {
  'assistantMessages' : bigint,
  'avgMessagesPerConversation' : bigint,
  'thumbsDown' : bigint,
  'totalMessages' : bigint,
  'periodEnd' : Timestamp,
  'thumbsUp' : bigint,
  'periodStart' : Timestamp,
  'avgResponseTime' : bigint,
  'totalConversations' : bigint,
}
export interface AiConfig {
  'personality' : AiPersonality,
  'businessId' : BusinessId,
  'temperature' : number,
  'tone' : ResponseTone,
  'updatedAt' : Timestamp,
  'systemPrompt' : string,
  'maxTokens' : bigint,
}
export type AiPersonality = { 'calm' : null } |
  { 'professional' : null } |
  { 'friendly' : null } |
  { 'witty' : null };
export interface AiResponseWithSources {
  'response' : string,
  'sources' : Array<SearchResult>,
}
export interface AnalyticsSnapshot {
  'teamSize' : bigint,
  'avgResolutionTime' : bigint,
  'totalMessages' : bigint,
  'resolvedTickets' : bigint,
  'periodEnd' : Timestamp,
  'openTickets' : bigint,
  'aiInteractions' : bigint,
  'periodStart' : Timestamp,
  'totalTickets' : bigint,
  'totalConversations' : bigint,
}
export type ApiResult = { 'ok' : boolean } |
  { 'err' : string };
export type ApiResult_1 = { 'ok' : KnowledgeBaseArticle } |
  { 'err' : string };
export type ApiResult_10 = { 'ok' : InviteLink } |
  { 'err' : string };
export type ApiResult_11 = { 'ok' : TicketAnalytics } |
  { 'err' : string };
export type ApiResult_12 = { 'ok' : TeamAnalytics } |
  { 'err' : string };
export type ApiResult_13 = { 'ok' : AnalyticsSnapshot } |
  { 'err' : string };
export type ApiResult_14 = { 'ok' : AiAnalytics } |
  { 'err' : string };
export type ApiResult_15 = { 'ok' : ExportedAnalytics } |
  { 'err' : string };
export type ApiResult_16 = { 'ok' : Conversation } |
  { 'err' : string };
export type ApiResult_17 = { 'ok' : CrawledPage } |
  { 'err' : string };
export type ApiResult_18 = { 'ok' : Feedback } |
  { 'err' : string };
export type ApiResult_2 = { 'ok' : User } |
  { 'err' : string };
export type ApiResult_3 = { 'ok' : Ticket } |
  { 'err' : string };
export type ApiResult_4 = { 'ok' : Customer } |
  { 'err' : string };
export type ApiResult_5 = { 'ok' : Business } |
  { 'err' : string };
export type ApiResult_6 = { 'ok' : null } |
  { 'err' : string };
export type ApiResult_7 = { 'ok' : AiResponseWithSources } |
  { 'err' : string };
export type ApiResult_8 = { 'ok' : string } |
  { 'err' : string };
export type ApiResult_9 = { 'ok' : ChatMessage } |
  { 'err' : string };
export type ArticleId = bigint;
export type AuditEventType = { 'LOGOUT' : null } |
  { 'EXPORT_DATA' : null } |
  { 'DELETE_TICKET' : null } |
  { 'UPDATE_CUSTOMER' : null } |
  { 'UPDATE_TICKET' : null } |
  { 'CREATE_TICKET' : null } |
  { 'CREATE_CUSTOMER' : null } |
  { 'UPDATE_SETTINGS' : null } |
  { 'INVITE_MEMBER' : null } |
  { 'LOGIN' : null } |
  { 'SEND_MESSAGE' : null };
export interface AuditLog {
  'id' : bigint,
  'principal' : Principal,
  'businessId' : [] | [BusinessId],
  'timestamp' : Timestamp,
  'details' : string,
  'eventType' : AuditEventType,
}
export interface Business {
  'id' : BusinessId,
  'teamSize' : string,
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'website' : [] | [string],
  'logoUrl' : [] | [string],
  'supportEmail' : string,
  'phoneNumber' : [] | [string],
  'industry' : string,
}
export type BusinessId = bigint;
export interface ChatMessage {
  'id' : MessageId,
  'content' : string,
  'role' : ChatMessageRole,
  'conversationId' : ConversationId,
  'timestamp' : Timestamp,
  'confidence' : [] | [number],
}
export type ChatMessageRole = { 'bot' : null } |
  { 'user' : null } |
  { 'assistant' : null };
export type ChunkId = bigint;
export interface Conversation {
  'id' : ConversationId,
  'title' : string,
  'businessId' : BusinessId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type ConversationId = bigint;
export interface CrawledPage {
  'id' : CrawledPageId,
  'url' : string,
  'title' : string,
  'content' : string,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
}
export type CrawledPageId = bigint;
export interface Customer {
  'id' : CustomerId,
  'businessId' : BusinessId,
  'name' : string,
  'createdAt' : Timestamp,
  'totalChats' : bigint,
  'tags' : Array<string>,
  'email' : string,
  'notes' : Array<CustomerNote>,
  'lastInteraction' : Timestamp,
}
export type CustomerId = bigint;
export interface CustomerNote {
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
}
export interface DocumentChunk {
  'id' : ChunkId,
  'content' : string,
  'chunkIndex' : bigint,
  'createdAt' : Timestamp,
  'articleId' : ArticleId,
}
export interface Embedding { 'chunkId' : ChunkId, 'vector' : Array<number> }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface ExportedAnalytics {
  'teamAnalytics' : TeamAnalytics,
  'overview' : AnalyticsSnapshot,
  'aiAnalytics' : AiAnalytics,
  'ticketAnalytics' : TicketAnalytics,
}
export interface ExportedChat {
  'title' : string,
  'businessId' : BusinessId,
  'messages' : Array<ChatMessage>,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'conversationId' : ConversationId,
}
export interface ExportedCustomer {
  'id' : CustomerId,
  'businessId' : BusinessId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
}
export interface ExportedTicket {
  'id' : TicketId,
  'status' : TicketStatus,
  'assignee' : [] | [UserId],
  'title' : string,
  'creator' : UserId,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'priority' : TicketPriority,
}
export interface Feedback {
  'id' : FeedbackId,
  'messageId' : MessageId,
  'createdAt' : Timestamp,
  'comment' : [] | [string],
  'conversationId' : ConversationId,
  'rating' : FeedbackRating,
}
export type FeedbackId = bigint;
export type FeedbackRating = { 'thumbsDown' : null } |
  { 'thumbsUp' : null };
export interface FeedbackStats {
  'total' : bigint,
  'thumbsDown' : bigint,
  'thumbsUp' : bigint,
  'thumbsUpPercentage' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type InviteId = bigint;
export interface InviteLink {
  'id' : InviteId,
  'expiresAt' : Timestamp,
  'businessId' : BusinessId,
  'code' : string,
  'createdBy' : UserId,
  'role' : UserRole,
  'used' : boolean,
  'revokedAt' : [] | [Timestamp],
}
export interface KnowledgeBaseArticle {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'category' : string,
}
export type MessageId = bigint;
export interface OtpRecord {
  'verified' : boolean,
  'code' : string,
  'createdAt' : Timestamp,
  'email' : string,
}
export interface PromptVersion {
  'id' : bigint,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'systemPrompt' : string,
  'versionNumber' : bigint,
}
export interface RateLimitEntry {
  'principal' : Principal,
  'endpoint' : string,
  'count' : bigint,
  'windowStart' : Timestamp,
}
export type RateLimitError = {
    'rateLimited' : { 'retryAfter' : bigint, 'message' : string }
  };
export type ResponseTone = { 'casual' : null } |
  { 'direct' : null } |
  { 'empathetic' : null } |
  { 'formal' : null };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface SearchResult { 'chunk' : DocumentChunk, 'score' : number }
export interface TeamAnalytics {
  'members' : Array<TeamMemberAnalytics>,
  'totalMembers' : bigint,
  'membersByRole' : {
    'admin' : bigint,
    'owner' : bigint,
    'supportAgent' : bigint,
    'viewer' : bigint,
  },
  'activeMembers' : bigint,
  'pendingInvites' : bigint,
}
export interface TeamMemberAnalytics {
  'name' : string,
  'agentId' : Principal,
  'ticketsResolved' : bigint,
  'ticketsAssigned' : bigint,
}
export interface Ticket {
  'id' : TicketId,
  'status' : TicketStatus,
  'assignee' : [] | [UserId],
  'title' : string,
  'creator' : UserId,
  'isDeleted' : [] | [boolean],
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'customerId' : [] | [UserId],
  'priority' : TicketPriority,
}
export interface TicketAnalytics {
  'resolved' : bigint,
  'closed' : bigint,
  'total' : bigint,
  'avgResolutionTime' : bigint,
  'open' : bigint,
  'periodEnd' : Timestamp,
  'periodStart' : Timestamp,
  'inProgress' : bigint,
  'byPriority' : {
    'low' : bigint,
    'high' : bigint,
    'urgent' : bigint,
    'medium' : bigint,
  },
}
export type TicketId = bigint;
export type TicketPriority = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface User {
  'id' : UserId,
  'principal' : Principal,
  'businessId' : [] | [BusinessId],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : [] | [string],
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'supportAgent' : null } |
  { 'viewer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ValidationError = { 'emptyInput' : null } |
  { 'tooLong' : bigint } |
  { 'containsHtml' : null } |
  { 'invalidLength' : null } |
  { 'invalidCharacters' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__aiConfigs' : ActorMethod<
    [[] | [BusinessId], [] | [bigint]],
    Array<[BusinessId, AiConfig]>
  >,
  '__articles' : ActorMethod<
    [[] | [ArticleId], [] | [bigint]],
    Array<[ArticleId, KnowledgeBaseArticle]>
  >,
  '__auditLogs' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, AuditLog]>
  >,
  '__businesses' : ActorMethod<
    [[] | [BusinessId], [] | [bigint]],
    Array<[BusinessId, Business]>
  >,
  '__chunks' : ActorMethod<
    [[] | [ChunkId], [] | [bigint]],
    Array<[ChunkId, DocumentChunk]>
  >,
  '__conversations' : ActorMethod<
    [[] | [ConversationId], [] | [bigint]],
    Array<[ConversationId, Conversation]>
  >,
  '__crawledPages' : ActorMethod<
    [[] | [CrawledPageId], [] | [bigint]],
    Array<[CrawledPageId, CrawledPage]>
  >,
  '__customers' : ActorMethod<
    [[] | [CustomerId], [] | [bigint]],
    Array<[CustomerId, Customer]>
  >,
  '__embeddings' : ActorMethod<
    [[] | [ChunkId], [] | [bigint]],
    Array<[ChunkId, Embedding]>
  >,
  '__feedbacks' : ActorMethod<
    [[] | [FeedbackId], [] | [bigint]],
    Array<[FeedbackId, Feedback]>
  >,
  '__geminiApiKey' : ActorMethod<[], any>,
  '__invites' : ActorMethod<
    [[] | [InviteId], [] | [bigint]],
    Array<[InviteId, InviteLink]>
  >,
  '__messages' : ActorMethod<
    [[] | [MessageId], [] | [bigint]],
    Array<[MessageId, ChatMessage]>
  >,
  '__nextArticleId' : ActorMethod<[], any>,
  '__nextAuditLogId' : ActorMethod<[], any>,
  '__nextBusinessId' : ActorMethod<[], any>,
  '__nextChunkId' : ActorMethod<[], any>,
  '__nextConversationId' : ActorMethod<[], any>,
  '__nextCrawledPageId' : ActorMethod<[], any>,
  '__nextCustomerId' : ActorMethod<[], any>,
  '__nextFeedbackId' : ActorMethod<[], any>,
  '__nextInviteId' : ActorMethod<[], any>,
  '__nextMessageId' : ActorMethod<[], any>,
  '__nextPromptVersionId' : ActorMethod<[], any>,
  '__nextTicketId' : ActorMethod<[], any>,
  '__otps' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, OtpRecord]>
  >,
  '__promptVersions' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, PromptVersion]>
  >,
  '__rateLimits' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, RateLimitEntry]>
  >,
  '__tickets' : ActorMethod<
    [[] | [TicketId], [] | [bigint]],
    Array<[TicketId, Ticket]>
  >,
  '__users' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, User]>
  >,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'acceptInvite' : ActorMethod<[string], ApiResult_10>,
  'addCustomerNote' : ActorMethod<[CustomerId, string], ApiResult_4>,
  'addCustomerTag' : ActorMethod<[CustomerId, string], ApiResult_4>,
  'addFeedback' : ActorMethod<
    [MessageId, ConversationId, FeedbackRating, [] | [string]],
    ApiResult_18
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'checkRateLimit' : ActorMethod<[string], [] | [RateLimitError]>,
  'crawlWebsite' : ActorMethod<
    [BusinessId, string, string, string],
    ApiResult_17
  >,
  'createArticle' : ActorMethod<
    [BusinessId, string, string, string],
    ApiResult_1
  >,
  'createBusiness' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      string,
      [] | [string],
      string,
      [] | [string],
    ],
    ApiResult_5
  >,
  'createConversation' : ActorMethod<[BusinessId, string], ApiResult_16>,
  'createCustomer' : ActorMethod<[BusinessId, string, string], ApiResult_4>,
  'createInvite' : ActorMethod<
    [BusinessId, string, UserRole, bigint],
    ApiResult_10
  >,
  'createTicket' : ActorMethod<
    [BusinessId, string, string, TicketPriority, TicketStatus, [] | [UserId]],
    ApiResult_3
  >,
  'deleteArticle' : ActorMethod<[ArticleId], ApiResult_6>,
  'deleteBusiness' : ActorMethod<[BusinessId], ApiResult_6>,
  'deleteConversation' : ActorMethod<[ConversationId], ApiResult_6>,
  'deleteCustomer' : ActorMethod<[CustomerId], ApiResult_6>,
  'deleteTicket' : ActorMethod<[TicketId], ApiResult_6>,
  'exportAnalytics' : ActorMethod<[BusinessId, bigint, bigint], ApiResult_15>,
  'exportChats' : ActorMethod<[BusinessId], Array<ExportedChat>>,
  'exportCustomers' : ActorMethod<[BusinessId], Array<ExportedCustomer>>,
  'exportTickets' : ActorMethod<[BusinessId], Array<ExportedTicket>>,
  'generateOtp' : ActorMethod<[string], ApiResult_8>,
  'getActivityTimeline' : ActorMethod<
    [BusinessId, bigint],
    Array<ActivityEvent>
  >,
  'getAiAnalytics' : ActorMethod<[BusinessId, bigint, bigint], ApiResult_14>,
  'getArticle' : ActorMethod<[ArticleId], [] | [KnowledgeBaseArticle]>,
  'getArticles' : ActorMethod<[BusinessId], Array<KnowledgeBaseArticle>>,
  'getAuditLogs' : ActorMethod<[BusinessId, bigint], Array<AuditLog>>,
  'getBusiness' : ActorMethod<[BusinessId], [] | [Business]>,
  'getCallerUser' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConversations' : ActorMethod<[BusinessId], Array<Conversation>>,
  'getCrawledPages' : ActorMethod<[BusinessId], Array<CrawledPage>>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getCustomers' : ActorMethod<[BusinessId], Array<Customer>>,
  'getFeedbackByConversation' : ActorMethod<[ConversationId], Array<Feedback>>,
  'getFeedbackStats' : ActorMethod<[], FeedbackStats>,
  'getGeminiApiKey' : ActorMethod<[], [] | [string]>,
  'getInviteByCode' : ActorMethod<[string], [] | [InviteLink]>,
  'getInvites' : ActorMethod<[BusinessId], Array<InviteLink>>,
  'getMessages' : ActorMethod<[ConversationId], Array<ChatMessage>>,
  'getMyAuditLogs' : ActorMethod<[bigint], Array<AuditLog>>,
  'getMyBusiness' : ActorMethod<[], [] | [Business]>,
  'getOverview' : ActorMethod<[BusinessId, bigint, bigint], ApiResult_13>,
  'getSimulatedOtp' : ActorMethod<[string], [] | [string]>,
  'getTeamAnalytics' : ActorMethod<[BusinessId], ApiResult_12>,
  'getTicket' : ActorMethod<[TicketId], [] | [Ticket]>,
  'getTicketAnalytics' : ActorMethod<
    [BusinessId, bigint, bigint],
    ApiResult_11
  >,
  'getTickets' : ActorMethod<[BusinessId], Array<Ticket>>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserRole' : ActorMethod<[Principal], [] | [UserRole]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, [] | [string]], ApiResult_2>,
  'removeCustomerTag' : ActorMethod<[CustomerId, string], ApiResult_4>,
  'removeTeamMember' : ActorMethod<[Principal], ApiResult_2>,
  'revokeInvite' : ActorMethod<[InviteId], ApiResult_10>,
  'sanitizeInput' : ActorMethod<[string], string>,
  'searchKnowledgeBase' : ActorMethod<
    [BusinessId, string, bigint],
    Array<SearchResult>
  >,
  'sendMessage' : ActorMethod<
    [ConversationId, ChatMessageRole, string, [] | [number]],
    ApiResult_9
  >,
  'sendToGemini' : ActorMethod<[ConversationId, string], ApiResult_8>,
  'sendToGeminiWithSources' : ActorMethod<
    [ConversationId, string],
    ApiResult_7
  >,
  'setGeminiApiKey' : ActorMethod<[string], ApiResult_6>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArticle' : ActorMethod<
    [ArticleId, [] | [string], [] | [string], [] | [string]],
    ApiResult_1
  >,
  'updateBusiness' : ActorMethod<
    [
      BusinessId,
      string,
      string,
      [] | [string],
      string,
      string,
      [] | [string],
      string,
      [] | [string],
    ],
    ApiResult_5
  >,
  'updateCustomer' : ActorMethod<
    [CustomerId, [] | [string], [] | [string]],
    ApiResult_4
  >,
  'updateTicket' : ActorMethod<
    [
      TicketId,
      [] | [string],
      [] | [string],
      [] | [TicketStatus],
      [] | [TicketPriority],
      [] | [UserId],
    ],
    ApiResult_3
  >,
  'updateUserRole' : ActorMethod<[Principal, UserRole], ApiResult_2>,
  'uploadDocumentChunks' : ActorMethod<
    [BusinessId, string, string, string],
    ApiResult_1
  >,
  'validateInput' : ActorMethod<
    [string, bigint, bigint, boolean],
    [] | [ValidationError]
  >,
  'verifyOtp' : ActorMethod<[string, string], ApiResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];