/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessId = IDL.Nat;
export const AiPersonality = IDL.Variant({
  'calm' : IDL.Null,
  'professional' : IDL.Null,
  'friendly' : IDL.Null,
  'witty' : IDL.Null,
});
export const ResponseTone = IDL.Variant({
  'casual' : IDL.Null,
  'direct' : IDL.Null,
  'empathetic' : IDL.Null,
  'formal' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const AiConfig = IDL.Record({
  'personality' : AiPersonality,
  'businessId' : BusinessId,
  'temperature' : IDL.Float64,
  'tone' : ResponseTone,
  'updatedAt' : Timestamp,
  'systemPrompt' : IDL.Text,
  'maxTokens' : IDL.Nat,
});
export const ArticleId = IDL.Nat;
export const KnowledgeBaseArticle = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'category' : IDL.Text,
});
export const AuditEventType = IDL.Variant({
  'LOGOUT' : IDL.Null,
  'EXPORT_DATA' : IDL.Null,
  'DELETE_TICKET' : IDL.Null,
  'UPDATE_CUSTOMER' : IDL.Null,
  'UPDATE_TICKET' : IDL.Null,
  'CREATE_TICKET' : IDL.Null,
  'CREATE_CUSTOMER' : IDL.Null,
  'UPDATE_SETTINGS' : IDL.Null,
  'INVITE_MEMBER' : IDL.Null,
  'LOGIN' : IDL.Null,
  'SEND_MESSAGE' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'businessId' : IDL.Opt(BusinessId),
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'eventType' : AuditEventType,
});
export const UserId = IDL.Principal;
export const Business = IDL.Record({
  'id' : BusinessId,
  'teamSize' : IDL.Text,
  'ownerId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'logoUrl' : IDL.Opt(IDL.Text),
  'supportEmail' : IDL.Text,
  'phoneNumber' : IDL.Opt(IDL.Text),
  'industry' : IDL.Text,
});
export const ChunkId = IDL.Nat;
export const DocumentChunk = IDL.Record({
  'id' : ChunkId,
  'content' : IDL.Text,
  'chunkIndex' : IDL.Nat,
  'createdAt' : Timestamp,
  'articleId' : ArticleId,
});
export const ConversationId = IDL.Nat;
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'businessId' : BusinessId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const CrawledPageId = IDL.Nat;
export const CrawledPage = IDL.Record({
  'id' : CrawledPageId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
});
export const CustomerId = IDL.Nat;
export const CustomerNote = IDL.Record({
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'businessId' : BusinessId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'totalChats' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'notes' : IDL.Vec(CustomerNote),
  'lastInteraction' : Timestamp,
});
export const Embedding = IDL.Record({
  'chunkId' : ChunkId,
  'vector' : IDL.Vec(IDL.Float64),
});
export const FeedbackId = IDL.Nat;
export const MessageId = IDL.Nat;
export const FeedbackRating = IDL.Variant({
  'thumbsDown' : IDL.Null,
  'thumbsUp' : IDL.Null,
});
export const Feedback = IDL.Record({
  'id' : FeedbackId,
  'messageId' : MessageId,
  'createdAt' : Timestamp,
  'comment' : IDL.Opt(IDL.Text),
  'conversationId' : ConversationId,
  'rating' : FeedbackRating,
});
export const InviteId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'owner' : IDL.Null,
  'supportAgent' : IDL.Null,
  'viewer' : IDL.Null,
});
export const InviteLink = IDL.Record({
  'id' : InviteId,
  'expiresAt' : Timestamp,
  'businessId' : BusinessId,
  'code' : IDL.Text,
  'createdBy' : UserId,
  'role' : UserRole,
  'used' : IDL.Bool,
  'revokedAt' : IDL.Opt(Timestamp),
});
export const ChatMessageRole = IDL.Variant({
  'bot' : IDL.Null,
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'role' : ChatMessageRole,
  'conversationId' : ConversationId,
  'timestamp' : Timestamp,
  'confidence' : IDL.Opt(IDL.Float64),
});
export const OtpRecord = IDL.Record({
  'verified' : IDL.Bool,
  'code' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const PromptVersion = IDL.Record({
  'id' : IDL.Nat,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'systemPrompt' : IDL.Text,
  'versionNumber' : IDL.Nat,
});
export const RateLimitEntry = IDL.Record({
  'principal' : IDL.Principal,
  'endpoint' : IDL.Text,
  'count' : IDL.Nat,
  'windowStart' : Timestamp,
});
export const TicketId = IDL.Nat;
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TicketPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : TicketId,
  'status' : TicketStatus,
  'assignee' : IDL.Opt(UserId),
  'title' : IDL.Text,
  'creator' : UserId,
  'isDeleted' : IDL.Opt(IDL.Bool),
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'customerId' : IDL.Opt(UserId),
  'priority' : TicketPriority,
});
export const User = IDL.Record({
  'id' : UserId,
  'principal' : IDL.Principal,
  'businessId' : IDL.Opt(BusinessId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ApiResult_10 = IDL.Variant({
  'ok' : InviteLink,
  'err' : IDL.Text,
});
export const ApiResult_4 = IDL.Variant({ 'ok' : Customer, 'err' : IDL.Text });
export const ApiResult_18 = IDL.Variant({ 'ok' : Feedback, 'err' : IDL.Text });
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RateLimitError = IDL.Variant({
  'rateLimited' : IDL.Record({ 'retryAfter' : IDL.Nat, 'message' : IDL.Text }),
});
export const ApiResult_17 = IDL.Variant({
  'ok' : CrawledPage,
  'err' : IDL.Text,
});
export const ApiResult_1 = IDL.Variant({
  'ok' : KnowledgeBaseArticle,
  'err' : IDL.Text,
});
export const ApiResult_5 = IDL.Variant({ 'ok' : Business, 'err' : IDL.Text });
export const ApiResult_16 = IDL.Variant({
  'ok' : Conversation,
  'err' : IDL.Text,
});
export const ApiResult_3 = IDL.Variant({ 'ok' : Ticket, 'err' : IDL.Text });
export const ApiResult_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const TeamMemberAnalytics = IDL.Record({
  'name' : IDL.Text,
  'agentId' : IDL.Principal,
  'ticketsResolved' : IDL.Nat,
  'ticketsAssigned' : IDL.Nat,
});
export const TeamAnalytics = IDL.Record({
  'members' : IDL.Vec(TeamMemberAnalytics),
  'totalMembers' : IDL.Nat,
  'membersByRole' : IDL.Record({
    'admin' : IDL.Nat,
    'owner' : IDL.Nat,
    'supportAgent' : IDL.Nat,
    'viewer' : IDL.Nat,
  }),
  'activeMembers' : IDL.Nat,
  'pendingInvites' : IDL.Nat,
});
export const AnalyticsSnapshot = IDL.Record({
  'teamSize' : IDL.Nat,
  'avgResolutionTime' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'resolvedTickets' : IDL.Nat,
  'periodEnd' : Timestamp,
  'openTickets' : IDL.Nat,
  'aiInteractions' : IDL.Nat,
  'periodStart' : Timestamp,
  'totalTickets' : IDL.Nat,
  'totalConversations' : IDL.Nat,
});
export const AiAnalytics = IDL.Record({
  'assistantMessages' : IDL.Nat,
  'avgMessagesPerConversation' : IDL.Nat,
  'thumbsDown' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'periodEnd' : Timestamp,
  'thumbsUp' : IDL.Nat,
  'periodStart' : Timestamp,
  'avgResponseTime' : IDL.Nat,
  'totalConversations' : IDL.Nat,
});
export const TicketAnalytics = IDL.Record({
  'resolved' : IDL.Nat,
  'closed' : IDL.Nat,
  'total' : IDL.Nat,
  'avgResolutionTime' : IDL.Nat,
  'open' : IDL.Nat,
  'periodEnd' : Timestamp,
  'periodStart' : Timestamp,
  'inProgress' : IDL.Nat,
  'byPriority' : IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'urgent' : IDL.Nat,
    'medium' : IDL.Nat,
  }),
});
export const ExportedAnalytics = IDL.Record({
  'teamAnalytics' : TeamAnalytics,
  'overview' : AnalyticsSnapshot,
  'aiAnalytics' : AiAnalytics,
  'ticketAnalytics' : TicketAnalytics,
});
export const ApiResult_15 = IDL.Variant({
  'ok' : ExportedAnalytics,
  'err' : IDL.Text,
});
export const ExportedChat = IDL.Record({
  'title' : IDL.Text,
  'businessId' : BusinessId,
  'messages' : IDL.Vec(ChatMessage),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'conversationId' : ConversationId,
});
export const ExportedCustomer = IDL.Record({
  'id' : CustomerId,
  'businessId' : BusinessId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const ExportedTicket = IDL.Record({
  'id' : TicketId,
  'status' : TicketStatus,
  'assignee' : IDL.Opt(UserId),
  'title' : IDL.Text,
  'creator' : UserId,
  'businessId' : BusinessId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'priority' : TicketPriority,
});
export const ApiResult_8 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ActivityEvent = IDL.Record({
  'principal' : IDL.Principal,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'eventType' : AuditEventType,
});
export const ApiResult_14 = IDL.Variant({
  'ok' : AiAnalytics,
  'err' : IDL.Text,
});
export const FeedbackStats = IDL.Record({
  'total' : IDL.Nat,
  'thumbsDown' : IDL.Nat,
  'thumbsUp' : IDL.Nat,
  'thumbsUpPercentage' : IDL.Nat,
});
export const ApiResult_13 = IDL.Variant({
  'ok' : AnalyticsSnapshot,
  'err' : IDL.Text,
});
export const ApiResult_12 = IDL.Variant({
  'ok' : TeamAnalytics,
  'err' : IDL.Text,
});
export const ApiResult_11 = IDL.Variant({
  'ok' : TicketAnalytics,
  'err' : IDL.Text,
});
export const ApiResult_2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const SearchResult = IDL.Record({
  'chunk' : DocumentChunk,
  'score' : IDL.Float64,
});
export const ApiResult_9 = IDL.Variant({
  'ok' : ChatMessage,
  'err' : IDL.Text,
});
export const AiResponseWithSources = IDL.Record({
  'response' : IDL.Text,
  'sources' : IDL.Vec(SearchResult),
});
export const ApiResult_7 = IDL.Variant({
  'ok' : AiResponseWithSources,
  'err' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const ValidationError = IDL.Variant({
  'emptyInput' : IDL.Null,
  'tooLong' : IDL.Nat,
  'containsHtml' : IDL.Null,
  'invalidLength' : IDL.Null,
  'invalidCharacters' : IDL.Null,
});
export const ApiResult = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__aiConfigs' : IDL.Func(
      [IDL.Opt(BusinessId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(BusinessId, AiConfig))],
      ['query'],
    ),
  '__articles' : IDL.Func(
      [IDL.Opt(ArticleId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(ArticleId, KnowledgeBaseArticle))],
      ['query'],
    ),
  '__auditLogs' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, AuditLog))],
      ['query'],
    ),
  '__businesses' : IDL.Func(
      [IDL.Opt(BusinessId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(BusinessId, Business))],
      ['query'],
    ),
  '__chunks' : IDL.Func(
      [IDL.Opt(ChunkId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(ChunkId, DocumentChunk))],
      ['query'],
    ),
  '__conversations' : IDL.Func(
      [IDL.Opt(ConversationId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(ConversationId, Conversation))],
      ['query'],
    ),
  '__crawledPages' : IDL.Func(
      [IDL.Opt(CrawledPageId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(CrawledPageId, CrawledPage))],
      ['query'],
    ),
  '__customers' : IDL.Func(
      [IDL.Opt(CustomerId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(CustomerId, Customer))],
      ['query'],
    ),
  '__embeddings' : IDL.Func(
      [IDL.Opt(ChunkId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(ChunkId, Embedding))],
      ['query'],
    ),
  '__feedbacks' : IDL.Func(
      [IDL.Opt(FeedbackId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(FeedbackId, Feedback))],
      ['query'],
    ),
  '__geminiApiKey' : IDL.Func([], [IDL.Reserved], ['query']),
  '__invites' : IDL.Func(
      [IDL.Opt(InviteId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(InviteId, InviteLink))],
      ['query'],
    ),
  '__messages' : IDL.Func(
      [IDL.Opt(MessageId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(MessageId, ChatMessage))],
      ['query'],
    ),
  '__nextArticleId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextAuditLogId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextBusinessId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextChunkId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextConversationId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextCrawledPageId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextCustomerId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextFeedbackId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextInviteId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextPromptVersionId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextTicketId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__otps' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, OtpRecord))],
      ['query'],
    ),
  '__promptVersions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PromptVersion))],
      ['query'],
    ),
  '__rateLimits' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, RateLimitEntry))],
      ['query'],
    ),
  '__tickets' : IDL.Func(
      [IDL.Opt(TicketId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(TicketId, Ticket))],
      ['query'],
    ),
  '__users' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
      ['query'],
    ),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptInvite' : IDL.Func([IDL.Text], [ApiResult_10], []),
  'addCustomerNote' : IDL.Func([CustomerId, IDL.Text], [ApiResult_4], []),
  'addCustomerTag' : IDL.Func([CustomerId, IDL.Text], [ApiResult_4], []),
  'addFeedback' : IDL.Func(
      [MessageId, ConversationId, FeedbackRating, IDL.Opt(IDL.Text)],
      [ApiResult_18],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'checkRateLimit' : IDL.Func([IDL.Text], [IDL.Opt(RateLimitError)], ['query']),
  'crawlWebsite' : IDL.Func(
      [BusinessId, IDL.Text, IDL.Text, IDL.Text],
      [ApiResult_17],
      [],
    ),
  'createArticle' : IDL.Func(
      [BusinessId, IDL.Text, IDL.Text, IDL.Text],
      [ApiResult_1],
      [],
    ),
  'createBusiness' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [ApiResult_5],
      [],
    ),
  'createConversation' : IDL.Func([BusinessId, IDL.Text], [ApiResult_16], []),
  'createCustomer' : IDL.Func(
      [BusinessId, IDL.Text, IDL.Text],
      [ApiResult_4],
      [],
    ),
  'createInvite' : IDL.Func(
      [BusinessId, IDL.Text, UserRole, IDL.Nat],
      [ApiResult_10],
      [],
    ),
  'createTicket' : IDL.Func(
      [
        BusinessId,
        IDL.Text,
        IDL.Text,
        TicketPriority,
        TicketStatus,
        IDL.Opt(UserId),
      ],
      [ApiResult_3],
      [],
    ),
  'deleteArticle' : IDL.Func([ArticleId], [ApiResult_6], []),
  'deleteBusiness' : IDL.Func([BusinessId], [ApiResult_6], []),
  'deleteConversation' : IDL.Func([ConversationId], [ApiResult_6], []),
  'deleteCustomer' : IDL.Func([CustomerId], [ApiResult_6], []),
  'deleteTicket' : IDL.Func([TicketId], [ApiResult_6], []),
  'exportAnalytics' : IDL.Func(
      [BusinessId, IDL.Nat, IDL.Nat],
      [ApiResult_15],
      ['query'],
    ),
  'exportChats' : IDL.Func([BusinessId], [IDL.Vec(ExportedChat)], ['query']),
  'exportCustomers' : IDL.Func(
      [BusinessId],
      [IDL.Vec(ExportedCustomer)],
      ['query'],
    ),
  'exportTickets' : IDL.Func(
      [BusinessId],
      [IDL.Vec(ExportedTicket)],
      ['query'],
    ),
  'generateOtp' : IDL.Func([IDL.Text], [ApiResult_8], []),
  'getActivityTimeline' : IDL.Func(
      [BusinessId, IDL.Nat],
      [IDL.Vec(ActivityEvent)],
      ['query'],
    ),
  'getAiAnalytics' : IDL.Func(
      [BusinessId, IDL.Nat, IDL.Nat],
      [ApiResult_14],
      ['query'],
    ),
  'getArticle' : IDL.Func(
      [ArticleId],
      [IDL.Opt(KnowledgeBaseArticle)],
      ['query'],
    ),
  'getArticles' : IDL.Func(
      [BusinessId],
      [IDL.Vec(KnowledgeBaseArticle)],
      ['query'],
    ),
  'getAuditLogs' : IDL.Func(
      [BusinessId, IDL.Nat],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'getBusiness' : IDL.Func([BusinessId], [IDL.Opt(Business)], ['query']),
  'getCallerUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getConversations' : IDL.Func(
      [BusinessId],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'getCrawledPages' : IDL.Func([BusinessId], [IDL.Vec(CrawledPage)], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getCustomers' : IDL.Func([BusinessId], [IDL.Vec(Customer)], ['query']),
  'getFeedbackByConversation' : IDL.Func(
      [ConversationId],
      [IDL.Vec(Feedback)],
      ['query'],
    ),
  'getFeedbackStats' : IDL.Func([], [FeedbackStats], ['query']),
  'getGeminiApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getInviteByCode' : IDL.Func([IDL.Text], [IDL.Opt(InviteLink)], ['query']),
  'getInvites' : IDL.Func([BusinessId], [IDL.Vec(InviteLink)], ['query']),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(ChatMessage)], ['query']),
  'getMyAuditLogs' : IDL.Func([IDL.Nat], [IDL.Vec(AuditLog)], ['query']),
  'getMyBusiness' : IDL.Func([], [IDL.Opt(Business)], ['query']),
  'getOverview' : IDL.Func(
      [BusinessId, IDL.Nat, IDL.Nat],
      [ApiResult_13],
      ['query'],
    ),
  'getSimulatedOtp' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getTeamAnalytics' : IDL.Func([BusinessId], [ApiResult_12], ['query']),
  'getTicket' : IDL.Func([TicketId], [IDL.Opt(Ticket)], ['query']),
  'getTicketAnalytics' : IDL.Func(
      [BusinessId, IDL.Nat, IDL.Nat],
      [ApiResult_11],
      ['query'],
    ),
  'getTickets' : IDL.Func([BusinessId], [IDL.Vec(Ticket)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [ApiResult_2], []),
  'removeCustomerTag' : IDL.Func([CustomerId, IDL.Text], [ApiResult_4], []),
  'removeTeamMember' : IDL.Func([IDL.Principal], [ApiResult_2], []),
  'revokeInvite' : IDL.Func([InviteId], [ApiResult_10], []),
  'sanitizeInput' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'searchKnowledgeBase' : IDL.Func(
      [BusinessId, IDL.Text, IDL.Nat],
      [IDL.Vec(SearchResult)],
      ['query'],
    ),
  'sendMessage' : IDL.Func(
      [ConversationId, ChatMessageRole, IDL.Text, IDL.Opt(IDL.Float64)],
      [ApiResult_9],
      [],
    ),
  'sendToGemini' : IDL.Func([ConversationId, IDL.Text], [ApiResult_8], []),
  'sendToGeminiWithSources' : IDL.Func(
      [ConversationId, IDL.Text],
      [ApiResult_7],
      [],
    ),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [ApiResult_6], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArticle' : IDL.Func(
      [ArticleId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ApiResult_1],
      [],
    ),
  'updateBusiness' : IDL.Func(
      [
        BusinessId,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [ApiResult_5],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [CustomerId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ApiResult_4],
      [],
    ),
  'updateTicket' : IDL.Func(
      [
        TicketId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(TicketStatus),
        IDL.Opt(TicketPriority),
        IDL.Opt(UserId),
      ],
      [ApiResult_3],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [ApiResult_2], []),
  'uploadDocumentChunks' : IDL.Func(
      [BusinessId, IDL.Text, IDL.Text, IDL.Text],
      [ApiResult_1],
      [],
    ),
  'validateInput' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Opt(ValidationError)],
      ['query'],
    ),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [ApiResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessId = IDL.Nat;
  const AiPersonality = IDL.Variant({
    'calm' : IDL.Null,
    'professional' : IDL.Null,
    'friendly' : IDL.Null,
    'witty' : IDL.Null,
  });
  const ResponseTone = IDL.Variant({
    'casual' : IDL.Null,
    'direct' : IDL.Null,
    'empathetic' : IDL.Null,
    'formal' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const AiConfig = IDL.Record({
    'personality' : AiPersonality,
    'businessId' : BusinessId,
    'temperature' : IDL.Float64,
    'tone' : ResponseTone,
    'updatedAt' : Timestamp,
    'systemPrompt' : IDL.Text,
    'maxTokens' : IDL.Nat,
  });
  const ArticleId = IDL.Nat;
  const KnowledgeBaseArticle = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'businessId' : BusinessId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'category' : IDL.Text,
  });
  const AuditEventType = IDL.Variant({
    'LOGOUT' : IDL.Null,
    'EXPORT_DATA' : IDL.Null,
    'DELETE_TICKET' : IDL.Null,
    'UPDATE_CUSTOMER' : IDL.Null,
    'UPDATE_TICKET' : IDL.Null,
    'CREATE_TICKET' : IDL.Null,
    'CREATE_CUSTOMER' : IDL.Null,
    'UPDATE_SETTINGS' : IDL.Null,
    'INVITE_MEMBER' : IDL.Null,
    'LOGIN' : IDL.Null,
    'SEND_MESSAGE' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'businessId' : IDL.Opt(BusinessId),
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'eventType' : AuditEventType,
  });
  const UserId = IDL.Principal;
  const Business = IDL.Record({
    'id' : BusinessId,
    'teamSize' : IDL.Text,
    'ownerId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'logoUrl' : IDL.Opt(IDL.Text),
    'supportEmail' : IDL.Text,
    'phoneNumber' : IDL.Opt(IDL.Text),
    'industry' : IDL.Text,
  });
  const ChunkId = IDL.Nat;
  const DocumentChunk = IDL.Record({
    'id' : ChunkId,
    'content' : IDL.Text,
    'chunkIndex' : IDL.Nat,
    'createdAt' : Timestamp,
    'articleId' : ArticleId,
  });
  const ConversationId = IDL.Nat;
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'businessId' : BusinessId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const CrawledPageId = IDL.Nat;
  const CrawledPage = IDL.Record({
    'id' : CrawledPageId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'businessId' : BusinessId,
    'createdAt' : Timestamp,
  });
  const CustomerId = IDL.Nat;
  const CustomerNote = IDL.Record({
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'businessId' : BusinessId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'totalChats' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'notes' : IDL.Vec(CustomerNote),
    'lastInteraction' : Timestamp,
  });
  const Embedding = IDL.Record({
    'chunkId' : ChunkId,
    'vector' : IDL.Vec(IDL.Float64),
  });
  const FeedbackId = IDL.Nat;
  const MessageId = IDL.Nat;
  const FeedbackRating = IDL.Variant({
    'thumbsDown' : IDL.Null,
    'thumbsUp' : IDL.Null,
  });
  const Feedback = IDL.Record({
    'id' : FeedbackId,
    'messageId' : MessageId,
    'createdAt' : Timestamp,
    'comment' : IDL.Opt(IDL.Text),
    'conversationId' : ConversationId,
    'rating' : FeedbackRating,
  });
  const InviteId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'supportAgent' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const InviteLink = IDL.Record({
    'id' : InviteId,
    'expiresAt' : Timestamp,
    'businessId' : BusinessId,
    'code' : IDL.Text,
    'createdBy' : UserId,
    'role' : UserRole,
    'used' : IDL.Bool,
    'revokedAt' : IDL.Opt(Timestamp),
  });
  const ChatMessageRole = IDL.Variant({
    'bot' : IDL.Null,
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'role' : ChatMessageRole,
    'conversationId' : ConversationId,
    'timestamp' : Timestamp,
    'confidence' : IDL.Opt(IDL.Float64),
  });
  const OtpRecord = IDL.Record({
    'verified' : IDL.Bool,
    'code' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const PromptVersion = IDL.Record({
    'id' : IDL.Nat,
    'businessId' : BusinessId,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'systemPrompt' : IDL.Text,
    'versionNumber' : IDL.Nat,
  });
  const RateLimitEntry = IDL.Record({
    'principal' : IDL.Principal,
    'endpoint' : IDL.Text,
    'count' : IDL.Nat,
    'windowStart' : Timestamp,
  });
  const TicketId = IDL.Nat;
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TicketPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'id' : TicketId,
    'status' : TicketStatus,
    'assignee' : IDL.Opt(UserId),
    'title' : IDL.Text,
    'creator' : UserId,
    'isDeleted' : IDL.Opt(IDL.Bool),
    'businessId' : BusinessId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'customerId' : IDL.Opt(UserId),
    'priority' : TicketPriority,
  });
  const User = IDL.Record({
    'id' : UserId,
    'principal' : IDL.Principal,
    'businessId' : IDL.Opt(BusinessId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ApiResult_10 = IDL.Variant({ 'ok' : InviteLink, 'err' : IDL.Text });
  const ApiResult_4 = IDL.Variant({ 'ok' : Customer, 'err' : IDL.Text });
  const ApiResult_18 = IDL.Variant({ 'ok' : Feedback, 'err' : IDL.Text });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RateLimitError = IDL.Variant({
    'rateLimited' : IDL.Record({
      'retryAfter' : IDL.Nat,
      'message' : IDL.Text,
    }),
  });
  const ApiResult_17 = IDL.Variant({ 'ok' : CrawledPage, 'err' : IDL.Text });
  const ApiResult_1 = IDL.Variant({
    'ok' : KnowledgeBaseArticle,
    'err' : IDL.Text,
  });
  const ApiResult_5 = IDL.Variant({ 'ok' : Business, 'err' : IDL.Text });
  const ApiResult_16 = IDL.Variant({ 'ok' : Conversation, 'err' : IDL.Text });
  const ApiResult_3 = IDL.Variant({ 'ok' : Ticket, 'err' : IDL.Text });
  const ApiResult_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const TeamMemberAnalytics = IDL.Record({
    'name' : IDL.Text,
    'agentId' : IDL.Principal,
    'ticketsResolved' : IDL.Nat,
    'ticketsAssigned' : IDL.Nat,
  });
  const TeamAnalytics = IDL.Record({
    'members' : IDL.Vec(TeamMemberAnalytics),
    'totalMembers' : IDL.Nat,
    'membersByRole' : IDL.Record({
      'admin' : IDL.Nat,
      'owner' : IDL.Nat,
      'supportAgent' : IDL.Nat,
      'viewer' : IDL.Nat,
    }),
    'activeMembers' : IDL.Nat,
    'pendingInvites' : IDL.Nat,
  });
  const AnalyticsSnapshot = IDL.Record({
    'teamSize' : IDL.Nat,
    'avgResolutionTime' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'resolvedTickets' : IDL.Nat,
    'periodEnd' : Timestamp,
    'openTickets' : IDL.Nat,
    'aiInteractions' : IDL.Nat,
    'periodStart' : Timestamp,
    'totalTickets' : IDL.Nat,
    'totalConversations' : IDL.Nat,
  });
  const AiAnalytics = IDL.Record({
    'assistantMessages' : IDL.Nat,
    'avgMessagesPerConversation' : IDL.Nat,
    'thumbsDown' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'periodEnd' : Timestamp,
    'thumbsUp' : IDL.Nat,
    'periodStart' : Timestamp,
    'avgResponseTime' : IDL.Nat,
    'totalConversations' : IDL.Nat,
  });
  const TicketAnalytics = IDL.Record({
    'resolved' : IDL.Nat,
    'closed' : IDL.Nat,
    'total' : IDL.Nat,
    'avgResolutionTime' : IDL.Nat,
    'open' : IDL.Nat,
    'periodEnd' : Timestamp,
    'periodStart' : Timestamp,
    'inProgress' : IDL.Nat,
    'byPriority' : IDL.Record({
      'low' : IDL.Nat,
      'high' : IDL.Nat,
      'urgent' : IDL.Nat,
      'medium' : IDL.Nat,
    }),
  });
  const ExportedAnalytics = IDL.Record({
    'teamAnalytics' : TeamAnalytics,
    'overview' : AnalyticsSnapshot,
    'aiAnalytics' : AiAnalytics,
    'ticketAnalytics' : TicketAnalytics,
  });
  const ApiResult_15 = IDL.Variant({
    'ok' : ExportedAnalytics,
    'err' : IDL.Text,
  });
  const ExportedChat = IDL.Record({
    'title' : IDL.Text,
    'businessId' : BusinessId,
    'messages' : IDL.Vec(ChatMessage),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'conversationId' : ConversationId,
  });
  const ExportedCustomer = IDL.Record({
    'id' : CustomerId,
    'businessId' : BusinessId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const ExportedTicket = IDL.Record({
    'id' : TicketId,
    'status' : TicketStatus,
    'assignee' : IDL.Opt(UserId),
    'title' : IDL.Text,
    'creator' : UserId,
    'businessId' : BusinessId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'priority' : TicketPriority,
  });
  const ApiResult_8 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ActivityEvent = IDL.Record({
    'principal' : IDL.Principal,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'eventType' : AuditEventType,
  });
  const ApiResult_14 = IDL.Variant({ 'ok' : AiAnalytics, 'err' : IDL.Text });
  const FeedbackStats = IDL.Record({
    'total' : IDL.Nat,
    'thumbsDown' : IDL.Nat,
    'thumbsUp' : IDL.Nat,
    'thumbsUpPercentage' : IDL.Nat,
  });
  const ApiResult_13 = IDL.Variant({
    'ok' : AnalyticsSnapshot,
    'err' : IDL.Text,
  });
  const ApiResult_12 = IDL.Variant({ 'ok' : TeamAnalytics, 'err' : IDL.Text });
  const ApiResult_11 = IDL.Variant({
    'ok' : TicketAnalytics,
    'err' : IDL.Text,
  });
  const ApiResult_2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const SearchResult = IDL.Record({
    'chunk' : DocumentChunk,
    'score' : IDL.Float64,
  });
  const ApiResult_9 = IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text });
  const AiResponseWithSources = IDL.Record({
    'response' : IDL.Text,
    'sources' : IDL.Vec(SearchResult),
  });
  const ApiResult_7 = IDL.Variant({
    'ok' : AiResponseWithSources,
    'err' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const ValidationError = IDL.Variant({
    'emptyInput' : IDL.Null,
    'tooLong' : IDL.Nat,
    'containsHtml' : IDL.Null,
    'invalidLength' : IDL.Null,
    'invalidCharacters' : IDL.Null,
  });
  const ApiResult = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__aiConfigs' : IDL.Func(
        [IDL.Opt(BusinessId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(BusinessId, AiConfig))],
        ['query'],
      ),
    '__articles' : IDL.Func(
        [IDL.Opt(ArticleId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(ArticleId, KnowledgeBaseArticle))],
        ['query'],
      ),
    '__auditLogs' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, AuditLog))],
        ['query'],
      ),
    '__businesses' : IDL.Func(
        [IDL.Opt(BusinessId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(BusinessId, Business))],
        ['query'],
      ),
    '__chunks' : IDL.Func(
        [IDL.Opt(ChunkId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(ChunkId, DocumentChunk))],
        ['query'],
      ),
    '__conversations' : IDL.Func(
        [IDL.Opt(ConversationId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(ConversationId, Conversation))],
        ['query'],
      ),
    '__crawledPages' : IDL.Func(
        [IDL.Opt(CrawledPageId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(CrawledPageId, CrawledPage))],
        ['query'],
      ),
    '__customers' : IDL.Func(
        [IDL.Opt(CustomerId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(CustomerId, Customer))],
        ['query'],
      ),
    '__embeddings' : IDL.Func(
        [IDL.Opt(ChunkId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(ChunkId, Embedding))],
        ['query'],
      ),
    '__feedbacks' : IDL.Func(
        [IDL.Opt(FeedbackId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(FeedbackId, Feedback))],
        ['query'],
      ),
    '__geminiApiKey' : IDL.Func([], [IDL.Reserved], ['query']),
    '__invites' : IDL.Func(
        [IDL.Opt(InviteId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(InviteId, InviteLink))],
        ['query'],
      ),
    '__messages' : IDL.Func(
        [IDL.Opt(MessageId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(MessageId, ChatMessage))],
        ['query'],
      ),
    '__nextArticleId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextAuditLogId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextBusinessId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextChunkId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextConversationId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextCrawledPageId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextCustomerId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextFeedbackId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextInviteId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextMessageId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextPromptVersionId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextTicketId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__otps' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, OtpRecord))],
        ['query'],
      ),
    '__promptVersions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PromptVersion))],
        ['query'],
      ),
    '__rateLimits' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, RateLimitEntry))],
        ['query'],
      ),
    '__tickets' : IDL.Func(
        [IDL.Opt(TicketId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(TicketId, Ticket))],
        ['query'],
      ),
    '__users' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
        ['query'],
      ),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptInvite' : IDL.Func([IDL.Text], [ApiResult_10], []),
    'addCustomerNote' : IDL.Func([CustomerId, IDL.Text], [ApiResult_4], []),
    'addCustomerTag' : IDL.Func([CustomerId, IDL.Text], [ApiResult_4], []),
    'addFeedback' : IDL.Func(
        [MessageId, ConversationId, FeedbackRating, IDL.Opt(IDL.Text)],
        [ApiResult_18],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'checkRateLimit' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RateLimitError)],
        ['query'],
      ),
    'crawlWebsite' : IDL.Func(
        [BusinessId, IDL.Text, IDL.Text, IDL.Text],
        [ApiResult_17],
        [],
      ),
    'createArticle' : IDL.Func(
        [BusinessId, IDL.Text, IDL.Text, IDL.Text],
        [ApiResult_1],
        [],
      ),
    'createBusiness' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [ApiResult_5],
        [],
      ),
    'createConversation' : IDL.Func([BusinessId, IDL.Text], [ApiResult_16], []),
    'createCustomer' : IDL.Func(
        [BusinessId, IDL.Text, IDL.Text],
        [ApiResult_4],
        [],
      ),
    'createInvite' : IDL.Func(
        [BusinessId, IDL.Text, UserRole, IDL.Nat],
        [ApiResult_10],
        [],
      ),
    'createTicket' : IDL.Func(
        [
          BusinessId,
          IDL.Text,
          IDL.Text,
          TicketPriority,
          TicketStatus,
          IDL.Opt(UserId),
        ],
        [ApiResult_3],
        [],
      ),
    'deleteArticle' : IDL.Func([ArticleId], [ApiResult_6], []),
    'deleteBusiness' : IDL.Func([BusinessId], [ApiResult_6], []),
    'deleteConversation' : IDL.Func([ConversationId], [ApiResult_6], []),
    'deleteCustomer' : IDL.Func([CustomerId], [ApiResult_6], []),
    'deleteTicket' : IDL.Func([TicketId], [ApiResult_6], []),
    'exportAnalytics' : IDL.Func(
        [BusinessId, IDL.Nat, IDL.Nat],
        [ApiResult_15],
        ['query'],
      ),
    'exportChats' : IDL.Func([BusinessId], [IDL.Vec(ExportedChat)], ['query']),
    'exportCustomers' : IDL.Func(
        [BusinessId],
        [IDL.Vec(ExportedCustomer)],
        ['query'],
      ),
    'exportTickets' : IDL.Func(
        [BusinessId],
        [IDL.Vec(ExportedTicket)],
        ['query'],
      ),
    'generateOtp' : IDL.Func([IDL.Text], [ApiResult_8], []),
    'getActivityTimeline' : IDL.Func(
        [BusinessId, IDL.Nat],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getAiAnalytics' : IDL.Func(
        [BusinessId, IDL.Nat, IDL.Nat],
        [ApiResult_14],
        ['query'],
      ),
    'getArticle' : IDL.Func(
        [ArticleId],
        [IDL.Opt(KnowledgeBaseArticle)],
        ['query'],
      ),
    'getArticles' : IDL.Func(
        [BusinessId],
        [IDL.Vec(KnowledgeBaseArticle)],
        ['query'],
      ),
    'getAuditLogs' : IDL.Func(
        [BusinessId, IDL.Nat],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getBusiness' : IDL.Func([BusinessId], [IDL.Opt(Business)], ['query']),
    'getCallerUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getConversations' : IDL.Func(
        [BusinessId],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'getCrawledPages' : IDL.Func(
        [BusinessId],
        [IDL.Vec(CrawledPage)],
        ['query'],
      ),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getCustomers' : IDL.Func([BusinessId], [IDL.Vec(Customer)], ['query']),
    'getFeedbackByConversation' : IDL.Func(
        [ConversationId],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getFeedbackStats' : IDL.Func([], [FeedbackStats], ['query']),
    'getGeminiApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getInviteByCode' : IDL.Func([IDL.Text], [IDL.Opt(InviteLink)], ['query']),
    'getInvites' : IDL.Func([BusinessId], [IDL.Vec(InviteLink)], ['query']),
    'getMessages' : IDL.Func(
        [ConversationId],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getMyAuditLogs' : IDL.Func([IDL.Nat], [IDL.Vec(AuditLog)], ['query']),
    'getMyBusiness' : IDL.Func([], [IDL.Opt(Business)], ['query']),
    'getOverview' : IDL.Func(
        [BusinessId, IDL.Nat, IDL.Nat],
        [ApiResult_13],
        ['query'],
      ),
    'getSimulatedOtp' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getTeamAnalytics' : IDL.Func([BusinessId], [ApiResult_12], ['query']),
    'getTicket' : IDL.Func([TicketId], [IDL.Opt(Ticket)], ['query']),
    'getTicketAnalytics' : IDL.Func(
        [BusinessId, IDL.Nat, IDL.Nat],
        [ApiResult_11],
        ['query'],
      ),
    'getTickets' : IDL.Func([BusinessId], [IDL.Vec(Ticket)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [ApiResult_2], []),
    'removeCustomerTag' : IDL.Func([CustomerId, IDL.Text], [ApiResult_4], []),
    'removeTeamMember' : IDL.Func([IDL.Principal], [ApiResult_2], []),
    'revokeInvite' : IDL.Func([InviteId], [ApiResult_10], []),
    'sanitizeInput' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'searchKnowledgeBase' : IDL.Func(
        [BusinessId, IDL.Text, IDL.Nat],
        [IDL.Vec(SearchResult)],
        ['query'],
      ),
    'sendMessage' : IDL.Func(
        [ConversationId, ChatMessageRole, IDL.Text, IDL.Opt(IDL.Float64)],
        [ApiResult_9],
        [],
      ),
    'sendToGemini' : IDL.Func([ConversationId, IDL.Text], [ApiResult_8], []),
    'sendToGeminiWithSources' : IDL.Func(
        [ConversationId, IDL.Text],
        [ApiResult_7],
        [],
      ),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [ApiResult_6], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArticle' : IDL.Func(
        [ArticleId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ApiResult_1],
        [],
      ),
    'updateBusiness' : IDL.Func(
        [
          BusinessId,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [ApiResult_5],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [CustomerId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ApiResult_4],
        [],
      ),
    'updateTicket' : IDL.Func(
        [
          TicketId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(TicketStatus),
          IDL.Opt(TicketPriority),
          IDL.Opt(UserId),
        ],
        [ApiResult_3],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [ApiResult_2], []),
    'uploadDocumentChunks' : IDL.Func(
        [BusinessId, IDL.Text, IDL.Text, IDL.Text],
        [ApiResult_1],
        [],
      ),
    'validateInput' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Opt(ValidationError)],
        ['query'],
      ),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [ApiResult], []),
  });
};

export const init = ({ IDL }) => { return []; };